### ISSUE TITLE
The webserver does not work

### ISSUE THREAD

**Issue by thedrow** [hyde/hyde#160]
I created a new project using hyde create and then tried to serve it using hyde serve and the server just hangs forever for http://127.0.0.1:8080 and just returns 404 for http://localhost:8080
When I accessed http://127.0.0.1:8080 I got the following traceback
Exception happened during processing of request from ('127.0.0.1', 60578)
Traceback (most recent call last):
  File "C:\Python27\Lib\SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\Lib\SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\Lib\SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\Lib\SocketServer.py", line 639, in __init__
    self.handle()
  File "C:\Python27\Lib\BaseHTTPServer.py", line 343, in handle
    self.handle_one_request()
  File "C:\Python27\Lib\BaseHTTPServer.py", line 313, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Python27\Lib\socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
What could be the problem?

**Comment by Descent098** [comment]
Closing this issue as it seems to have stagnated. If OP is still encountering the issue tag me in a comment and I can re-open the issue.
