### ISSUE TITLE
Missing requirement on argparse

### ISSUE THREAD

**Issue by atodorov** [hyde/hyde#247]
```
$ pip install hyde

... skip ...

$ pip freeze
Jinja2==2.7.1
Markdown==2.3.1
MarkupSafe==0.18
PyYAML==3.10
Pygments==1.6
commando==0.3.4
fswrap==0.1.2
hyde==0.8.8
smartypants==1.7.1
typogrify==2.0.0


$ hyde --help
Traceback (most recent call last):
  File "/home/atodorov/.virtualenvs/test/bin/hyde", line 9, in <module>
    load_entry_point('hyde==0.8.8', 'console_scripts', 'hyde')()
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/hyde/main.py", line 6, in <module>
    from hyde.engine import Engine
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/hyde/engine.py", line 7, in <module>
    from hyde.model import Config
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/hyde/model.py", line 10, in <module>
    from commando.util import getLoggerWithNullHandler
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/commando/__init__.py", line 2, in <module>
    from commando.application import *
  File "/home/atodorov/.virtualenvs/test/lib/python2.6/site-packages/commando/application.py", line 5, in <module>
    from argparse import ArgumentParser
ImportError: No module named argparse
```

**Comment by llonchj** [comment]
@atodorov, please update to Python 2.7
