### ISSUE TITLE
Can't find smartypants, even though it is installed

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [hyde/hyde#286]
I've got a Python 2.7 virtual environment into which hyde installed without error. But then hyde won't run without error.

Here's the list of installed packages, and a `which hyde` shows which instance of hyde will be invoked:

```
(venv27)[master]~/Documents/prj/moi/jenesuispasdave.github.io$
pip list
commando (0.3.4)
distribute (0.6.14)
fswrap (0.1.2)
hyde (0.8.8, /Users/datihein/Documents/prj/moi/jenesuispasdave.github.io/venv27/src/hyde)
Jinja2 (2.7.3)
Markdown (2.6.2)
MarkupSafe (0.23)
pip (7.1.0)
Pygments (2.0.2)
PyYAML (3.11)
setuptools (18.0.1)
smartypants (1.8.6)
typogrify (2.0.7)

(venv27)[master]~/Documents/prj/moi/jenesuispasdave.github.io$
which hyde
/Users/datihein/Documents/prj/moi/jenesuispasdave.github.io/venv27/bin/hyde
```

But when I run hyde, it seems it cannot find smartypants 1.8.6, even though it is installed:

```
(venv27)[master]~/Documents/prj/moi/jenesuispasdave.github.io$
hyde gen ./wat
Traceback (most recent call last):
  File "/Users/datihein/Documents/prj/moi/jenesuispasdave.github.io/venv27/bin/hyde", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2671, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 654, in require
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 552, in resolve
pkg_resources.DistributionNotFound: smartypants==1.8.6
```

**Comment by moggers87** [comment]
Can you run the following from within the same virtualenv:

`python -c "import smartypants; print smartypants.__version__"`

I don't trust pip list/freeze to always tell the truth :)

**Comment by JeNeSuisPasDave** [comment]
Confirming ...

```
(venv27)[master]~/Documents/prj/moi/jenesuispasdave.github.io$
python -c "import smartypants; print smartypants.__version__"
1.8.6
```
