### ISSUE TITLE
SyntaxError on raising exception, invalid syntax

### ISSUE THREAD

**Issue by teritriano** [hyde/hyde#306]
hyde is practically unusable. Any input to hyde raises the SyntaxError. Windows 10, Python 3.5

```
> hyde
Traceback (most recent call last):
  File "C:\Python35\Scripts\hyde-script.py", line 9, in <module>
    load_entry_point('hyde==0.8.9', 'console_scripts', 'hyde')()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\teritriano\src\hyde\hyde\main.py", line 6, in <module>
    from hyde.engine import Engine
  File "c:\users\teritriano\src\hyde\hyde\engine.py", line 5, in <module>
    from hyde.exceptions import HydeException
  File "c:\users\teritriano\src\hyde\hyde\exceptions.py", line 10
    raise HydeException(message), None, tb
                                ^
SyntaxError: invalid syntax
```

**Comment by jonafato** [comment]
Python 3 support is planned, but Hyde currently only works on Python 2. This issue will be fixed when #270 is addressed. This issue is effectively a subset of the other, so I'm closing it to keep discussion in one place. Updates will be posted to that issue's discussion thread.
