### ISSUE TITLE
SyntaxError when trying to create website

### ISSUE THREAD

**Issue by JXSnack** [hyde/hyde#350]
When I execute `hyde -s /path/to/your/site create` it returns this error.
```python
(.venv) joram@joram-mini MineNet Website % hyde -s minenet create
Traceback (most recent call last):
  File "/Users/joram/PyCharmProjects/MineNet Website/.venv/bin/hyde", line 7, in <module>
    from hyde.main import main
  File "/Users/joram/PycharmProjects/MineNet Website/.venv/lib/python3.9/site-packages/hyde/main.py", line 6, in <module>
    from hyde.engine import Engine
  File "/Users/joram/PycharmProjects/MineNet Website/.venv/lib/python3.9/site-packages/hyde/engine.py", line 5, in <module>
    from hyde.exceptions import HydeException
  File "/Users/joram/PycharmProjects/MineNet Website/.venv/lib/python3.9/site-packages/hyde/exceptions.py", line 10
    raise HydeException(message), None, tb
                                ^
SyntaxError: invalid syntax
```
Running Python 3.9.6
MacOS 14.0, M1 Chip

**Comment by Roester1** [comment]
sad

**Comment by navilan** [comment]
Hi @JXSnack - Hyde is unmaintained and I have no plans to restart development.

- If you are just looking for a good static website generator - use Astro JS
- You can also try nuejs which is created by someone closely associated with hyde.
- If you are particular about python - you can probably use pelican.

**Comment by codebykat** [comment]
Hi @navilan, sad to hear it's unmaintained. Any chance you could archive this repository, update the README and/or update the website with this statement? Would've saved me (and probably others) some time and trouble if it was stated more prominently. Thanks for all your work on this project.
